---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates (Ubuntu)
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: Install apache And php For Ubuntu Servers
      tags: apache,apache2,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: start apache2
      tags: apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"

    - name: Copy Default html File For Site
      tags: apache, apache2
      ansible.builtin.copy:
        src: files/default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb package (Ubuntu)
      tags: mariadb,db,ubuntu
      ansible.builtin.apt:
        name:
          - mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: Install samba Package
      tags: samba,file,ubuntu
      ansible.builtin.package:
        name: samba
        state: latest
    - name: Install unzip
      ansible.builtin.package:
        name: unzip

    - name: Install terraform
      ansible.builtin.unarchive:
        src: https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
        mode: 0755
        owner: root
        group: root
