---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (CentOS | Ubuntu)
      tags: always
      ansible.builtin.package:
        update_cache: yes
      changed_when: false
      when: ansible_distribution in ["CentOS", "Ubuntu"]

  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
